In [1]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
stocks = ["MSFT","AAPL","AMZN","NVDA","GOOGL"]

In [3]:
dfs=[]

for stock in stocks:
    df= yf.download(stock,start="2020-01-01", end="2025-12-31",
                    auto_adjust=False, progress= False)

    if isinstance(df.columns, pd.MultiIndex):
        df.columns= df.columns.get_level_values(0)


    df = df.reset_index()
    df["Ticker"]= stock

    dfs.append(df)

all_data=pd.concat(dfs, ignore_index=True)

all_data.head()

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker
0,2020-01-02,151.829559,160.619995,160.729996,158.330002,158.779999,22622100,MSFT
1,2020-01-03,149.938980,158.619995,159.949997,158.059998,158.320007,21116200,MSFT
2,2020-01-06,150.326538,159.029999,159.100006,156.509995,157.080002,20813700,MSFT
3,2020-01-07,148.955902,157.580002,159.669998,157.320007,159.320007,21634100,MSFT
4,2020-01-08,151.328552,160.089996,160.800003,157.949997,158.929993,27746500,MSFT

In [4]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7535 entries, 0 to 7534
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       7535 non-null   datetime64[ns]
 1   Adj Close  7535 non-null   float64
 2   Close      7535 non-null   float64
 3   High       7535 non-null   float64
 4   Low        7535 non-null   float64
 5   Open       7535 non-null   float64
 6   Volume     7535 non-null   int64
 7   Ticker     7535 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 471.1+ KB

In [5]:
all_data.isnull().sum()

Price
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
Ticker       0
dtype: int64

In [6]:
#Daily return percentage

all_data["Daily_Return"]= (all_data.groupby("Ticker")["Close"].pct_change()*100)

In [7]:
all_data.tail()

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker,Daily_Return
7530,2025-12-23,313.941345,314.350006,314.940002,309.320007,309.630005,25478700,GOOGL,1.475243
7531,2025-12-24,313.681671,314.089996,315.079987,311.920013,314.769989,10097400,GOOGL,-0.082713
7532,2025-12-26,313.102478,313.510010,315.089996,312.279999,314.480011,10899000,GOOGL,-0.184656
7533,2025-12-29,313.152405,313.559998,314.019989,310.619995,311.369995,19621800,GOOGL,0.015945
7534,2025-12-30,313.442017,313.850006,316.950012,312.459991,312.500000,17380900,GOOGL,0.092489

In [8]:
all_data.head()

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker,Daily_Return
0,2020-01-02,151.829559,160.619995,160.729996,158.330002,158.779999,22622100,MSFT,NaN
1,2020-01-03,149.938980,158.619995,159.949997,158.059998,158.320007,21116200,MSFT,-1.245175
2,2020-01-06,150.326538,159.029999,159.100006,156.509995,157.080002,20813700,MSFT,0.258482
3,2020-01-07,148.955902,157.580002,159.669998,157.320007,159.320007,21634100,MSFT,-0.911776
4,2020-01-08,151.328552,160.089996,160.800003,157.949997,158.929993,27746500,MSFT,1.592838

In [9]:
#Price change

all_data["Price_change"]=( all_data["Close"] - all_data["Open"] )

In [10]:
# 20 Day Moving AVerage

all_data["20MA"]=( all_data.groupby("Ticker")["Close"].transform
                   (lambda x: x.rolling(20).mean())
                 )

In [11]:
all_data.iloc[20:50]

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker,Daily_Return,Price_change,20MA
20,2020-01-31,160.913635,170.229996,172.399994,169.580002,172.210007,36142700,MSFT,-1.475867,-1.980011,164.167999
21,2020-02-03,164.836502,174.380005,174.500000,170.399994,170.429993,30107000,MSFT,2.437884,3.950012,164.955999
22,2020-02-04,170.262360,180.119995,180.639999,176.309998,177.139999,36433300,MSFT,3.291656,2.979996,166.010499
23,2020-02-05,170.054382,179.899994,184.199997,178.410004,184.029999,39186300,MSFT,-0.122141,-4.130005,167.126498
24,2020-02-06,173.580246,183.630005,183.820007,180.059998,180.970001,27751400,MSFT,2.073380,2.660004,168.303499
25,2020-02-07,173.826065,183.889999,185.630005,182.479996,182.850006,33529100,MSFT,0.141586,1.039993,169.393499
26,2020-02-10,178.372772,188.699997,188.839996,183.250000,183.580002,35844300,MSFT,2.615693,5.119995,170.761499
27,2020-02-11,174.345947,184.440002,190.699997,183.500000,190.649994,53159900,MSFT,-2.257549,-6.209991,171.819499
28,2020-02-12,174.601120,184.710007,185.850006,181.850006,185.580002,47062900,MSFT,0.146391,-0.869995,172.948499
29,2020-02-13,173.655914,183.710007,186.229996,182.869995,183.080002,35295800,MSFT,-0.541389,0.630005,173.975000
30,2020-02-14,175.206100,185.350006,185.410004,182.649994,183.250000,23149500,MSFT,0.892711,2.100006,174.934000
31,2020-02-18,176.983200,187.229996,187.699997,185.500000,185.610001,27792200,MSFT,1.014292,1.619995,175.940500
32,2020-02-19,177.514053,187.279999,188.179993,186.470001,188.059998,29997500,MSFT,0.026707,-0.779999,176.979500
33,2020-02-20,174.803162,184.419998,187.250000,181.100006,186.949997,36862400,MSFT,-1.527125,-2.529999,177.915500
34,2020-02-21,169.277161,178.589996,183.500000,177.250000,183.169998,48572600,MSFT,-3.161263,-4.580002,178.509000
35,2020-02-24,161.978745,170.889999,174.550003,163.229996,167.770004,68311100,MSFT,-4.311550,3.119995,178.801500
36,2020-02-25,159.305771,168.070007,174.839996,167.649994,174.199997,68073300,MSFT,-1.650180,-6.129990,179.091000
37,2020-02-26,161.296265,170.169998,173.259995,168.210007,169.710007,56206100,MSFT,1.249474,0.459991,179.326500
38,2020-02-27,149.931488,158.179993,167.029999,157.979996,163.320007,93174900,MSFT,-7.045899,-5.140015,178.833500
39,2020-02-28,153.561768,162.009995,163.710007,152.000000,152.410004,97012700,MSFT,2.421293,9.599991,178.295000
40,2020-03-02,163.779633,172.789993,172.919998,162.309998,165.309998,71030800,MSFT,6.653910,7.479996,178.423000
41,2020-03-03,155.931427,164.509995,175.000000,162.259995,173.800003,71677000,MSFT,-4.791943,-9.290009,177.929499
42,2020-03-04,161.656448,170.550003,170.699997,165.619995,168.490005,49814400,MSFT,3.671515,2.059998,177.450999
43,2020-03-05,157.599609,166.270004,170.869995,165.690002,166.050003,47817300,MSFT,-2.509527,0.220001,176.769500
44,2020-03-06,153.144745,161.570007,163.110001,156.000000,162.610001,72821100,MSFT,-2.826726,-1.039993,175.666500
45,2020-03-09,142.765701,150.619995,157.750000,150.000000,151.000000,70419300,MSFT,-6.777255,-0.380005,174.003000
46,2020-03-10,152.528595,160.919998,161.029999,152.580002,158.160004,65354400,MSFT,6.838404,2.759995,172.614000
47,2020-03-11,145.618774,153.630005,157.699997,151.149994,157.130005,56371600,MSFT,-4.530197,-3.500000,171.073500
48,2020-03-12,131.808548,139.059998,153.470001,138.580002,145.300003,93226400,MSFT,-9.483829,-6.240005,168.791000
49,2020-03-13,150.547592,158.830002,161.910004,140.729996,147.500000,92727400,MSFT,14.216888,11.330002,167.546999

In [28]:
# 50 day Moving Average
all_data["50MA"]= (all_data.groupby("Ticker")["Close"].transform
                   (lambda x:x.rolling(50).mean())
                  )

In [29]:
all_data[1000:1050]

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker,Daily_Return,Price_change,20MA,50MA,Volatility
1000,2023-12-21,366.420593,373.540009,374.410004,370.040009,372.559998,17708000,MSFT,0.787873,0.980011,373.671501,359.151403,0.976452
1001,2023-12-22,367.440765,374.579987,375.179993,372.709991,373.679993,17107500,MSFT,0.278411,0.899994,373.529001,360.019802,0.979109
1002,2023-12-26,367.519287,374.660004,376.940002,373.500000,375.000000,12673100,MSFT,0.021362,-0.339996,373.331502,360.958402,0.975853
1003,2023-12-27,366.940491,374.070007,375.059998,372.809998,373.690002,14905400,MSFT,-0.157475,0.380005,372.900002,361.787002,0.939097
1004,2023-12-28,368.127441,375.279999,376.459991,374.160004,375.369995,14327000,MSFT,0.323467,-0.089996,372.721501,362.651402,0.919159
1005,2023-12-29,368.872955,376.040009,377.160004,373.480011,376.000000,18730800,MSFT,0.202518,0.040009,372.578001,363.570002,0.920738
1006,2024-01-02,363.801453,370.869995,375.899994,366.769989,373.859985,25258600,MSFT,-1.374857,-2.989990,372.396001,364.361002,0.935623
1007,2024-01-03,363.536652,370.600006,373.260010,368.510010,369.010010,23083500,MSFT,-0.072799,1.589996,372.469000,365.239602,0.876915
1008,2024-01-04,360.927368,367.940002,373.100006,367.170013,370.670013,20901500,MSFT,-0.717756,-2.730011,372.240001,366.012002,0.865432
1009,2024-01-05,360.740967,367.750000,372.059998,366.500000,368.970001,21004600,MSFT,-0.051640,-1.220001,372.187502,366.756402,0.836705
1010,2024-01-08,367.548706,374.690002,375.200012,369.010010,369.299988,23134000,MSFT,1.887152,5.390015,372.374501,367.436802,0.930940
1011,2024-01-09,368.627747,375.790009,375.989990,371.190002,372.010010,20830000,MSFT,0.293578,3.779999,372.452501,368.394802,0.912411
1012,2024-01-10,375.474701,382.769989,384.170013,376.320007,376.369995,25514200,MSFT,1.857415,6.399994,373.026001,369.454001,0.978049
1013,2024-01-11,377.299225,384.630005,390.679993,380.380005,386.000000,27850800,MSFT,0.485936,-1.369995,373.538501,370.400402,0.968582
1014,2024-01-12,381.066101,388.470001,388.679993,384.649994,385.489990,21661200,MSFT,0.998361,2.980011,374.243501,371.407602,0.986541
1015,2024-01-16,382.831757,390.269989,394.029999,387.619995,393.660004,27202300,MSFT,0.463353,-3.390015,375.460501,372.291602,0.802099
1016,2024-01-17,382.047028,389.470001,390.109985,384.809998,387.980011,22234100,MSFT,-0.204983,1.489990,376.397501,373.114601,0.775200
1017,2024-01-18,386.363098,393.869995,393.989990,390.119995,391.720001,23392100,MSFT,1.129739,2.149994,377.458501,373.936002,0.798076
1018,2024-01-19,391.071716,398.670013,398.670013,393.500000,395.760010,29331100,MSFT,1.218681,2.910004,378.729001,374.778802,0.824394
1019,2024-01-22,388.952881,396.510010,400.619995,393.589996,400.019989,27016900,MSFT,-0.541802,-3.509979,380.023502,375.498402,0.814170
1020,2024-01-23,391.297333,398.899994,399.380005,393.929993,395.750000,20525900,MSFT,0.602755,3.149994,381.291501,376.212402,0.809867
1021,2024-01-24,394.887543,402.559998,405.630005,400.450012,401.540009,24867000,MSFT,0.917524,1.019989,382.690501,377.049802,0.820182
1022,2024-01-25,397.153473,404.869995,407.010010,402.529999,404.320007,21021200,MSFT,0.573827,0.549988,384.201001,377.753801,0.817332
1023,2024-01-26,396.231384,403.929993,406.170013,402.429993,404.369995,17803300,MSFT,-0.232174,-0.440002,385.694000,378.498801,0.820139
1024,2024-01-29,401.911102,409.720001,409.980011,404.329987,406.059998,24510200,MSFT,1.433419,3.660004,387.416000,379.287802,0.852466
1025,2024-01-30,400.802612,408.589996,413.049988,406.450012,412.260010,33477600,MSFT,-0.275799,-3.670013,389.043500,380.066201,0.866179
1026,2024-01-31,390.002441,397.579987,415.320007,397.209991,406.959991,47871100,MSFT,-2.694635,-9.380005,390.378999,380.494401,1.042418
1027,2024-02-01,396.084259,403.779999,408.000000,401.799988,401.829987,30657700,MSFT,1.559438,1.950012,392.037999,381.173000,1.070794
1028,2024-02-02,403.382446,411.220001,412.649994,403.559998,403.809998,28256700,MSFT,1.842588,7.410004,394.201999,381.848600,1.078729
1029,2024-02-05,397.918610,405.649994,411.160004,403.989990,409.899994,25352300,MSFT,-1.354508,-4.250000,396.096999,382.500200,1.154488
1030,2024-02-06,397.761658,405.489990,407.970001,402.910004,405.880005,18382600,MSFT,-0.039444,-0.390015,397.636998,383.053000,1.112075
1031,2024-02-07,406.158508,414.049988,414.299988,407.399994,407.440002,22340500,MSFT,2.111026,6.609985,399.549997,383.785400,1.175240
1032,2024-02-08,406.217377,414.109985,415.559998,412.529999,414.049988,21225300,MSFT,0.014490,0.059998,401.116997,384.495400,1.134122
1033,2024-02-09,412.534668,420.549988,420.820007,415.089996,415.250000,22032800,MSFT,1.555143,5.299988,402.912996,385.252399,1.163194
1034,2024-02-12,407.345459,415.260010,420.739990,414.750000,420.559998,21202900,MSFT,-1.257871,-5.299988,404.252496,385.980599,1.215824
1035,2024-02-13,398.575836,406.320007,410.070007,403.390015,404.940002,27824900,MSFT,-2.152869,1.380005,405.054997,386.528799,1.336703
1036,2024-02-14,402.428223,409.489990,409.839996,404.570007,408.070007,20401200,MSFT,0.780169,1.419983,406.055997,387.228399,1.338747
1037,2024-02-15,399.548828,406.559998,409.130005,404.290009,408.140015,21825500,MSFT,-0.715522,-1.580017,406.690497,387.976799,1.339200
1038,2024-02-16,397.091949,404.059998,408.290009,403.440002,407.959991,22296500,MSFT,-0.614915,-3.899994,406.959996,388.607599,1.326129
1039,2024-02-20,395.843842,402.790009,404.489990,398.010010,403.239990,24307900,MSFT,-0.314307,-0.449982,407.273996,389.287399,1.321523
1040,2024-02-21,395.244354,402.179993,402.290009,397.220001,400.170013,18518900,MSFT,-0.151448,2.009979,407.437996,389.911999,1.316781
1041,2024-02-22,404.550964,411.649994,412.829987,408.570007,410.190002,27009900,MSFT,2.354667,1.459991,407.892496,390.660399,1.403046
1042,2024-02-23,403.263580,410.339996,415.859985,408.970001,415.670013,16295900,MSFT,-0.318231,-5.330017,408.165996,391.441199,1.402074
1043,2024-02-26,400.511871,407.540009,412.160004,407.359985,411.459991,16193500,MSFT,-0.682358,-3.919983,408.346497,392.104399,1.410876
1044,2024-02-27,400.452942,407.480011,408.320007,403.850006,407.989990,14835800,MSFT,-0.014722,-0.509979,408.234497,392.766599,1.373006
1045,2024-02-28,400.688782,407.720001,409.299988,405.320007,408.179993,13183100,MSFT,0.058896,-0.459991,408.190997,393.602399,1.371744
1046,2024-02-29,406.506683,413.640015,414.200012,405.920013,408.640015,31947300,MSFT,1.451980,5.000000,408.993999,394.460599,1.251392
1047,2024-03-01,408.334625,415.500000,415.869995,410.880005,411.269989,17823400,MSFT,0.449663,4.230011,409.579999,395.317599,1.212192
1048,2024-03-04,407.764648,414.920013,417.350006,412.320007,413.440002,17596000,MSFT,-0.139588,1.480011,409.764999,396.150800,1.145743
1049,2024-03-05,395.706238,402.649994,414.250000,400.640015,413.959991,26919200,MSFT,-2.957201,-11.309998,409.614999,396.791400,1.295483

In [30]:
all_data.head()

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker,Daily_Return,Price_change,20MA,50MA,Volatility
0,2020-01-02,151.829559,160.619995,160.729996,158.330002,158.779999,22622100,MSFT,NaN,1.839996,NaN,NaN,NaN
1,2020-01-03,149.938980,158.619995,159.949997,158.059998,158.320007,21116200,MSFT,-1.245175,0.299988,NaN,NaN,NaN
2,2020-01-06,150.326538,159.029999,159.100006,156.509995,157.080002,20813700,MSFT,0.258482,1.949997,NaN,NaN,NaN
3,2020-01-07,148.955902,157.580002,159.669998,157.320007,159.320007,21634100,MSFT,-0.911776,-1.740005,NaN,NaN,NaN
4,2020-01-08,151.328552,160.089996,160.800003,157.949997,158.929993,27746500,MSFT,1.592838,1.160004,NaN,NaN,NaN

In [31]:
df.head()

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker
0,2020-01-02,67.832504,68.433998,68.433998,67.324501,67.420502,27278000,GOOGL
1,2020-01-03,67.477661,68.075996,68.687500,67.365997,67.400002,23408000,GOOGL
2,2020-01-06,69.276215,69.890503,69.916000,67.550003,67.581497,46768000,GOOGL
3,2020-01-07,69.142403,69.755501,70.175003,69.578003,70.023003,34330000,GOOGL
4,2020-01-08,69.634529,70.251999,70.592499,69.631500,69.740997,35314000,GOOGL

In [32]:
#Volatility

all_data["Volatility"] = (
    all_data.groupby("Ticker")["Daily_Return"]
            .transform(lambda x: x.rolling(20).std())
)

In [33]:
all_data.to_csv("stock_data.csv", index=False)